//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseOrganize
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Code { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Category { get; set; }
        public Nullable<int> Layer { get; set; }
        public string OuterPhone { get; set; }
        public string InnerPhone { get; set; }
        public string Fax { get; set; }
        public string Postalcode { get; set; }
        public string Address { get; set; }
        public string Web { get; set; }
        public Nullable<int> IsInnerOrganize { get; set; }
        public string Bank { get; set; }
        public string BankAccount { get; set; }
        public Nullable<int> DeletionStateCode { get; set; }
        public Nullable<int> Enabled { get; set; }
        public Nullable<int> SortCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public string ModifiedBy { get; set; }
    }
}
