//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseUser
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string UserName { get; set; }
        public string RealName { get; set; }
        public string QuickQuery { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> SecurityLevel { get; set; }
        public string UserFrom { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> SubCompanyId { get; set; }
        public string SubCompanyName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> WorkgroupId { get; set; }
        public string WorkgroupName { get; set; }
        public string WorkCategory { get; set; }
        public string Signature { get; set; }
        public string UserPassword { get; set; }
        public Nullable<System.DateTime> ChangePasswordDate { get; set; }
        public string CommunicationPassword { get; set; }
        public string SignedPassword { get; set; }
        public string PublicKey { get; set; }
        public string Duty { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Lang { get; set; }
        public string Gender { get; set; }
        public string Birthday { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string OICQ { get; set; }
        public string HomeAddress { get; set; }
        public string Theme { get; set; }
        public Nullable<System.DateTime> AllowStartTime { get; set; }
        public Nullable<System.DateTime> AllowEndTime { get; set; }
        public Nullable<System.DateTime> LockStartDate { get; set; }
        public Nullable<System.DateTime> LockEndDate { get; set; }
        public Nullable<System.DateTime> FirstVisit { get; set; }
        public Nullable<System.DateTime> PreviousVisit { get; set; }
        public Nullable<int> LogOnCount { get; set; }
        public Nullable<int> PasswordErrorCount { get; set; }
        public Nullable<int> IsStaff { get; set; }
        public Nullable<int> UserOnLine { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public string OpenId { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public string Question { get; set; }
        public string AnswerQuestion { get; set; }
        public string UserAddressId { get; set; }
        public Nullable<int> Enabled { get; set; }
        public string AuditStatus { get; set; }
        public Nullable<int> DeletionStateCode { get; set; }
        public Nullable<int> SortCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
    }
}
