//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseStaff
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public string RealName { get; set; }
        public string Code { get; set; }
        public string Gender { get; set; }
        public Nullable<int> SubCompanyId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> WorkgroupId { get; set; }
        public string QuickQuery { get; set; }
        public string DutyId { get; set; }
        public string IdentificationCode { get; set; }
        public string IDCard { get; set; }
        public string BankCode { get; set; }
        public string RewarCard { get; set; }
        public string MedicalCard { get; set; }
        public string UnionMember { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string ShortNumber { get; set; }
        public string Telephone { get; set; }
        public string OICQ { get; set; }
        public string OfficePhone { get; set; }
        public string OfficeZipCode { get; set; }
        public string OfficeAddress { get; set; }
        public string OfficeFax { get; set; }
        public string Age { get; set; }
        public string Birthday { get; set; }
        public string Education { get; set; }
        public string School { get; set; }
        public string GraduationDate { get; set; }
        public string Major { get; set; }
        public string Degree { get; set; }
        public string TitleId { get; set; }
        public string TitleDate { get; set; }
        public string TitleLevel { get; set; }
        public string WorkingDate { get; set; }
        public string JoinInDate { get; set; }
        public string HomeZipCode { get; set; }
        public string HomeAddress { get; set; }
        public string HomePhone { get; set; }
        public string HomeFax { get; set; }
        public string Province { get; set; }
        public string CarCode { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string NativePlace { get; set; }
        public string Party { get; set; }
        public string Nation { get; set; }
        public string Nationality { get; set; }
        public string WorkingProperty { get; set; }
        public string Competency { get; set; }
        public string EmergencyContact { get; set; }
        public Nullable<System.DateTime> Weddingday { get; set; }
        public Nullable<System.DateTime> Divorce { get; set; }
        public Nullable<System.DateTime> Childbirthday1 { get; set; }
        public Nullable<System.DateTime> Childbirthday2 { get; set; }
        public Nullable<int> IsDimission { get; set; }
        public string DimissionDate { get; set; }
        public string DimissionCause { get; set; }
        public string DimissionWhither { get; set; }
        public Nullable<int> Enabled { get; set; }
        public Nullable<int> DeletionStateCode { get; set; }
        public Nullable<int> SortCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public string ModifiedBy { get; set; }
    }
}
